// Generated by TMB: do not edit by hand

#define TMB_LIB_INIT R_init_MyTMBPackage_TMBExports
#include <TMB.hpp>
#include "ModelA.hpp"
#include "ModelB.hpp"
#include "ModelC.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "ModelA") {
    return ModelA(this);
  } else if(model == "ModelB") {
    return ModelB(this);
  } else if(model == "ModelC") {
    return ModelC(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
