#' Add \pkg{TMB} source code to an existing \R package.
#'
#' @export
use_tmb <- function(pkg = ".") {
  root <- .package_root(pkg)
  # update DESCRIPTION file
  desc <- file.path(root, "DESCRIPTION")
  x <- read.dcf(desc)
  pkg_name <- x[, "Package"]
  for(dep in c("Imports", "LinkingTo")) {
    if(dep %in% colnames(x)) {
      depval <- x[, dep]
      coll <- ifelse(grepl(",[[:space:]]*\n", depval), ",\n", ", ")
      x[, dep] <- paste0(c(depval, "TMB"), collapse = coll)
    } else {
      x <- cbind(x, "TMB")
      colnames(x)[ncol(x)] <- dep
    }
  }
  message("Updated 'DESCRIPTION'...")
  write.dcf(x, file = desc)

  # update NAMESPACE file
  nspc <- file.path(root, "NAMESPACE")
  x <- readLines(nspc)
  if(grepl("^# Generated by roxygen2:", x[1])) {
    if(file.exists(x <- file.path(root, "R", paste0(pkg_name, "-package.R")))) {
      # find useDynLib line
      x <- readLines(x)
      usedl_pref <- "^#+'[[:blank:]]*@useDynLib[[:blank:]]+"
      usedl_line <- grepl(paste0(usedl_pref, pkg_name), x)
      if(all(!usedl_line)) {
      } else {
        # insert useDynLib in last line
        if(getRversion() >= "3.4.0") {
          usedl <- sprintf("useDynLib(%s, .registration=TRUE)", name)
        } else {
          usedl <- sprintf("useDynLib(%s)", name)
        }
      }
    }
  }
}
