#--- helper functions ----------------------------------------------------------

# formats useDynLib
use_dynlib <- function(dynlibs) {
  out <- paste0("useDynLib(", dynlibs, ")")
  out <- paste0(out, collapse = "; ")
  out
}

# adds a file to the package
use_file <- function(fl, ...) {
  if(!file.exists(fl)) ui_stop("File {ui_path(fl)} doesn't exist.")
  file.copy(from = fl,
            to = file.path(usethis::proj_get(), ..., basename(fl)))
}

# silently executes usethis commands
use_silent <- function(code) {
  if(!missing(code)) {
    withr::with_options(list(usethis.quiet = TRUE), code = code)
  }
}

# needs init if src has no files (except directories)
check_needs_init <- function(root) {
  src_files <- dir(path = file.path(root, "src"), full.names = TRUE)
  length(src_files) == 0 || all(dir.exists(src_files))
}

# identical to usethis::use_template, except:
# 1. package defaults to TMBtools
# 2. never overwrites if file exists
use_template <- function(template, save_as = template,
                         data = list(), ignore = FALSE,
                         open = FALSE, package = "TMBtools") {
  usethis::local_project()
  if(file.exists(file.path(usethis::proj_get(), save_as))) {
    ui_line("File {ui_path(save_as)} already exists.  Not overwritten.")
  } else {
    usethis::use_template(template = template,
                          save_as = save_as,
                          data = data, ignore = ignore,
                          open = open, package = package)
  }
}

# get package name
get_package <- function(root) {
  read.dcf(file = file.path(root, "DESCRIPTION"), fields = "Package")[1]
}

# check if file was autogenerated by TMBtools
check_tmb_generated <- function(tmb_main) {
  tmb_str <- "// Generated by TMBtools: do not edit by hand"
  if(file.exists(tmb_main)) {
    if(readLines(tmb_main)[1] != tmb_str) {
      tmb_main <- paste0('src/TMB/', basename(tmb_main))
      ui_stop("{ui_path(tmb_main)} exists but not generated by TMBtools.  Not overwritten.")
    } else {
      file.remove(tmb_main)
    }
  }
}

# add TMB specific instructions to NAMESPACE file
add_tmb_namespace <- function(root, pkg, dynlibs) {
  nsp <- file.path(root, "NAMESPACE")
  # check if the NAMESPACE has the correct dynlibs
  has_nsp <- rm_white(use_dynlib(dynlibs))
  has_nsp <- gsub("([.]|\\(|\\))", "\\\\\\1", has_nsp)
  has_nsp <- file.exists(nsp) &&
    any(grepl(pattern = paste0("^(", has_nsp, ")$"),
              x = rm_white(readLines(nsp))))
  # check if package uses roxygen
  has_roxy <- !is.na(read.dcf(file.path(root, "DESCRIPTION"),
                              fields = "RoxygenNote")[1])
  if(!has_nsp) {
    if(!file.exists(nsp)) {
      # add Namespace file (probably only happens in tmb_create_package)
      use_template(template = "NAMESPACE", package = "TMBtools",
                   data = list(usedl = use_dynlib(dynlibs)))
    }
    if(has_roxy) {
      # check if package has "pkgname{-package}.R" file
      has_pkgdoc <- file.path(root, "R",
                              paste0(pkg, c(".R", "-package.R")))
      has_pkgdoc <- any(file.exists(has_pkgdoc))
      if(!has_pkgdoc) {
        # create a default usethis namespace
        use_template(template = "package.R", package = "TMBtools",
                     save_as = file.path("R", paste0(pkg, "-package.R")),
                     data = list(usedl = use_dynlib(dynlibs)))
        ui_done("Done!")
        ui_todo("run roxygen on package to update NAMESPACE.")
      } else {
        # user has to manually update namespace via roxygen
        ui_done("Done!")
        ui_todo("Add the following roxygen comment to update the NAMESPACE:")
        message()
        ui_code_block(paste0("#' @rawNamespace ", use_dynlib(dynlibs)))
        message("")
      }
    } else {
      # user has to manually update namespace by hand
      ui_done("Done!")
      ui_todo("Add the following line to the NAMESPACE file:\n")
      message("")
      ui_line(use_dynlib(dynlibs))
      message("")
    }
  } else {
    ui_done("Done!")
  }
}

# remove all whitespace from a character vector
rm_white <- function(x) gsub("[[:space:]]", "", x)
